#!/bin/bash

if [ "$1" = "-h" ] || [ "$1" = "-?" ]
then

cat help.txt | less

else

echo "Witaj $user"
echo "Program kalkulator"

sleep 3

zapytanie="t"

while [ "$zapytanie" = "t" ] || [ "$zapytanie" = "tak" ]
do

clear

echo -e "\nPodaj a="
read aa

echo "Podaj znak:"
read znak

echo "Podaj b="
read bb

case "$znak" in

     "+") echo "wynik z +"
     echo "$aa+$bb" | bc -l;;

     "-") echo "wynik z -"
     echo "$aa-$bb" | bc -l;;

     "*") echo "wynik z *"
     echo "$aa*$bb" | bc -l;;

     "/") echo "wynik z /"
     echo "scale=2 $aa/$bb" | bc -l;;

     *) echo "wybrales zly znak"

esac

echo "Czy chcesz dalej t/n (tak/nie)?:"
read zapytanie

done

fi

#echo "wynik z +" $((aa+bb))
#echo "wynik z -" $((aa-bb))
#echo "wynik z *" $((aa*bb))
#echo "wynik z /" $((aa/bb))
