#!/bin/bash
kon="t"

clear

if [ "$1" = "-h" ]
then cat help.txt | less

else

echo -e "\nWitaj $user"
echo -e "\nTo jest program ksiazka telefoniczna"

sleep 2

zapytanie="t"

while [ "$zapytanie" = "t" ] || [ "$zapytanie" = "tak" ]
do


echo -e "Co chcesz zrobic?"
echo -e "\t1. Dodac nowy kontakt;"
echo -e "\t2. Wyswietl dane;"
echo -e "\t3. Sortuj dane;"
echo -e "\t4. Wyswietl pomoc;"
echo -e "\t5. Wyszukaj osobe;"
echo -e "\t6. Usun osobe (linie);"
echo -e "\t0. Wyjscie z programu"
echo "Podaj numer (1,2,3,4,5,6 lub 0)"

read numer

case $numer in

        1)
                     ./dodawanie_danych.sh
        ;;

        2)
                     cat dane.txt | less
        ;;

        3)
                     sort -d dane.txt
        ;;

        4)
                     cat help.txt
        ;;

        5)           ./szukanie_osoby.sh

        ;;

        6)           ./usuwanie_linii.sh

        ;;
        0) echo "Dziekujemy za skorzystanie z naszego programu"

        ;;

        *) echo "Zly wybor"

esac

echo "Czy chcesz kontynuowac? (t/n):"
read zapytanie
done
fi


        
